language_codes = {
    "aa": { "Name": "Afar", "Source": "Äthiopien, Eritrea, Dschibuti" },
    "ab": { "Name": "Abchasisch", "Source": "Abchasien (Georgien)" },
    "ae": { "Name": "Avestisch", "Source": "Historische Sprache (Iran)" },
    "af": { "Name": "Afrikaans", "Source": "Südafrika, Namibia" },
    "ak": { "Name": "Akan", "Source": "Ghana" },
    "am": { "Name": "Amharisch", "Source": "Äthiopien" },
    "an": { "Name": "Aragonesisch", "Source": "Spanien (Aragon)" },
    "ar": { "Name": "Arabisch", "Source": "Naher Osten, Nordafrika" },
    "as": { "Name": "Assamesisch", "Source": "Indien (Assam)" },
    "av": { "Name": "Awarisch", "Source": "Russland (Dagestan)" },
    "ay": { "Name": "Aymara", "Source": "Bolivien, Peru" },
    "az": { "Name": "Aserbaidschanisch", "Source": "Aserbaidschan, Iran" },
    "ba": { "Name": "Baschkirisch", "Source": "Russland (Baschkortostan)" },
    "be": { "Name": "Weißrussisch", "Source": "Belarus" },
    "bg": { "Name": "Bulgarisch", "Source": "Bulgarien" },
    "bh": { "Name": "Bihari", "Source": "Indien (Bihar)" },
    "bi": { "Name": "Bislama", "Source": "Vanuatu" },
    "bm": { "Name": "Bambara", "Source": "Mali" },
    "bn": { "Name": "Bengalisch", "Source": "Bangladesch, Indien (Westbengalen)" },
    "bo": { "Name": "Tibetisch", "Source": "Tibet, China" },
    "br": { "Name": "Bretonisch", "Source": "Frankreich (Bretagne)" },
    "bs": { "Name": "Bosnisch", "Source": "Bosnien und Herzegowina" },
    "ca": { "Name": "Katalanisch", "Source": "Spanien (Katalonien), Andorra" },
    "ce": { "Name": "Tschetschenisch", "Source": "Russland (Tschetschenien)" },
    "ch": { "Name": "Chamorro", "Source": "Guam, Nördliche Marianen" },
    "co": { "Name": "Korsisch", "Source": "Frankreich (Korsika)" },
    "cr": { "Name": "Cree", "Source": "Kanada" },
    "cs": { "Name": "Tschechisch", "Source": "Tschechien" },
    "cu": { "Name": "Kirchenslawisch", "Source": "Historische Sprache (Osteuropa)" },
    "cv": { "Name": "Tschuwaschisch", "Source": "Russland (Tschuwaschien)" },
    "cy": { "Name": "Walisisch", "Source": "Wales, Vereinigtes Königreich" },
    "da": { "Name": "Dänisch", "Source": "Dänemark" },
    "de": { "Name": "Deutsch", "Source": "Deutschland, Österreich, Schweiz" },
    "dv": { "Name": "Dhivehi", "Source": "Malediven" },
    "dz": { "Name": "Dzongkha", "Source": "Bhutan" },
    "ee": { "Name": "Ewe", "Source": "Ghana, Togo" },
    "el": { "Name": "Griechisch", "Source": "Griechenland, Zypern" },
    "en": { "Name": "Englisch", "Source": "Global (USA, UK, Australien, etc.)" },
    "eo": { "Name": "Esperanto", "Source": "Künstliche Sprache, International" },
    "es": { "Name": "Spanisch", "Source": "Spanien, Lateinamerika" },
    "et": { "Name": "Estnisch", "Source": "Estland" },
    "eu": { "Name": "Baskisch", "Source": "Spanien (Baskenland), Frankreich" },
    "fa": { "Name": "Persisch", "Source": "Iran, Afghanistan" },
    "ff": { "Name": "Fulfulde", "Source": "Westafrika" },
    "fi": { "Name": "Finnisch", "Source": "Finnland" },
    "fj": { "Name": "Fidschianisch", "Source": "Fidschi" },
    "fo": { "Name": "Färöisch", "Source": "Färöer-Inseln (Dänemark)" },
    "fr": { "Name": "Französisch", "Source": "Frankreich, Kanada, Afrika" },
    "fy": { "Name": "Westfriesisch", "Source": "Niederlande (Friesland)" },
    "ga": { "Name": "Irisch", "Source": "Irland" },
    "gd": { "Name": "Gälisch-Schottisch", "Source": "Schottland" },
    "gl": { "Name": "Galicisch", "Source": "Spanien (Galicien)" },
    "gn": { "Name": "Guaraní", "Source": "Paraguay, Bolivien, Argentinien" },
    "gu": { "Name": "Gujarati", "Source": "Indien (Gujarat)" },
    "gv": { "Name": "Manx", "Source": "Isle of Man" },
    "ha": { "Name": "Hausa", "Source": "Nigeria, Niger" },
    "he": { "Name": "Hebräisch", "Source": "Israel" },
    "hi": { "Name": "Hindi", "Source": "Indien" },
    "ho": { "Name": "Hiri Motu", "Source": "Papua-Neuguinea" },
    "hr": { "Name": "Kroatisch", "Source": "Kroatien" },
    "ht": { "Name": "Haitianisch", "Source": "Haiti" },
    "hu": { "Name": "Ungarisch", "Source": "Ungarn" },
    "hy": { "Name": "Armenisch", "Source": "Armenien" },
    "hz": { "Name": "Herero", "Source": "Namibia" },
    "ia": { "Name": "Interlingua", "Source": "Künstliche Sprache, International" },
    "id": { "Name": "Indonesisch", "Source": "Indonesien" },
    "ie": { "Name": "Interlingue", "Source": "Künstliche Sprache, International" },
    "ig": { "Name": "Igbo", "Source": "Nigeria" },
    "ii": { "Name": "Sichuan Yi", "Source": "China (Sichuan)" },
    "ik": { "Name": "Inupiaq", "Source": "USA (Alaska)" },
    "io": { "Name": "Ido", "Source": "Künstliche Sprache, International" },
    "is": { "Name": "Isländisch", "Source": "Island" },
    "it": { "Name": "Italienisch", "Source": "Italien, Schweiz" },
    "iu": { "Name": "Inuktitut", "Source": "Kanada (Arktis)" },
    "ja": { "Name": "Japanisch", "Source": "Japan" },
    "jv": { "Name": "Javanisch", "Source": "Indonesien (Java)" },
    "ka": { "Name": "Georgisch", "Source": "Georgien" },
    "kg": { "Name": "Kikongo", "Source": "Republik Kongo, Demokratische Republik Kongo" },
    "ki": { "Name": "Kikuyu", "Source": "Kenia" },
    "kj": { "Name": "Kuanyama", "Source": "Angola, Namibia" },
    "kk": { "Name": "Kasachisch", "Source": "Kasachstan" },
    "kl": { "Name": "Grönländisch", "Source": "Grönland (Dänemark)" },
    "km": { "Name": "Khmer", "Source": "Kambodscha" },
    "kn": { "Name": "Kannada", "Source": "Indien (Karnataka)" },
    "ko": { "Name": "Koreanisch", "Source": "Südkorea, Nordkorea" },
    "kr": { "Name": "Kanuri", "Source": "Nigeria, Niger" },
    "ks": { "Name": "Kaschmiri", "Source": "Indien (Kaschmir)" },
    "ku": { "Name": "Kurdisch", "Source": "Türkei, Iran, Irak, Syrien" },
    "kv": { "Name": "Komi", "Source": "Russland (Komi)" },
    "kw": { "Name": "Kornisch", "Source": "Vereinigtes Königreich (Cornwall)" },
    "ky": { "Name": "Kirgisisch", "Source": "Kirgisistan" },
    "la": { "Name": "Lateinisch", "Source": "Historische Sprache (Europa)" },
    "lb": { "Name": "Luxemburgisch", "Source": "Luxemburg" },
    "lg": { "Name": "Luganda", "Source": "Uganda" },
    "li": { "Name": "Limburgisch", "Source": "Niederlande (Limburg), Belgien" },
    "ln": { "Name": "Lingala", "Source": "Demokratische Republik Kongo, Republik Kongo" },
    "lo": { "Name": "Laotisch", "Source": "Laos" },
    "lt": { "Name": "Litauisch", "Source": "Litauen" },
    "lu": { "Name": "Luba-Katanga", "Source": "Demokratische Republik Kongo" },
    "lv": { "Name": "Lettisch", "Source": "Lettland" },
    "mg": { "Name": "Madagassisch", "Source": "Madagaskar" },
    "mh": { "Name": "Marshallese", "Source": "Marshallinseln" },
    "mi": { "Name": "Maori", "Source": "Neuseeland" },
    "mk": { "Name": "Mazedonisch", "Source": "Nordmazedonien" },
    "ml": { "Name": "Malayalam", "Source": "Indien (Kerala)" },
    "mn": { "Name": "Mongolisch", "Source": "Mongolei" },
    "mr": { "Name": "Marathi", "Source": "Indien (Maharashtra)" },
    "ms": { "Name": "Malaysisch", "Source": "Malaysia, Brunei, Singapur" },
    "mt": { "Name": "Maltesisch", "Source": "Malta" },
    "my": { "Name": "Burmesisch", "Source": "Myanmar" },
    "na": { "Name": "Nauruisch", "Source": "Nauru" },
    "nb": { "Name": "Norwegisch (Bokmål)", "Source": "Norwegen" },
    "nd": { "Name": "Nord-Ndebele", "Source": "Simbabwe" },
    "ne": { "Name": "Nepalesisch", "Source": "Nepal, Indien" },
    "ng": { "Name": "Ndonga", "Source": "Namibia" },
    "nl": { "Name": "Niederländisch", "Source": "Niederlande, Belgien" },
    "nn": { "Name": "Norwegisch (Nynorsk)", "Source": "Norwegen" },
    "no": { "Name": "Norwegisch", "Source": "Norwegen" },
    "nr": { "Name": "Süd-Ndebele", "Source": "Südafrika" },
    "nv": { "Name": "Navajo", "Source": "USA (Südwesten)" },
    "ny": { "Name": "Nyanja", "Source": "Malawi, Sambia" },
    "oc": { "Name": "Okzitanisch", "Source": "Frankreich (Okzitanien)" },
    "oj": { "Name": "Ojibwa", "Source": "Kanada, USA" },
    "om": { "Name": "Oromo", "Source": "Äthiopien, Kenia" },
    "or": { "Name": "Oriya", "Source": "Indien (Odisha)" },
    "os": { "Name": "Ossetisch", "Source": "Russland (Nordossetien), Georgien" },
    "pa": { "Name": "Panjabi", "Source": "Indien (Punjab), Pakistan" },
    "pi": { "Name": "Pali", "Source": "Historische Sprache (Indien)" },
    "pl": { "Name": "Polnisch", "Source": "Polen" },
    "ps": { "Name": "Paschtu", "Source": "Afghanistan, Pakistan" },
    "pt": { "Name": "Portugiesisch", "Source": "Portugal, Brasilien" },
    "qu": { "Name": "Quechua", "Source": "Peru, Bolivien, Ecuador" },
    "rm": { "Name": "Rätoromanisch", "Source": "Schweiz (Graubünden)" },
    "rn": { "Name": "Rundi", "Source": "Burundi" },
    "ro": { "Name": "Rumänisch", "Source": "Rumänien, Moldawien" },
    "ru": { "Name": "Russisch", "Source": "Russland, Osteuropa" },
    "rw": { "Name": "Kinyarwanda", "Source": "Ruanda" },
    "sa": { "Name": "Sanskrit", "Source": "Historische Sprache (Indien)" },
    "sc": { "Name": "Sardisch", "Source": "Italien (Sardinien)" },
    "sd": { "Name": "Sindhi", "Source": "Pakistan, Indien" },
    "se": { "Name": "Nordsamisch", "Source": "Norwegen, Schweden, Finnland" },
    "sg": { "Name": "Sango", "Source": "Zentralafrikanische Republik" },
    "si": { "Name": "Singhalesisch", "Source": "Sri Lanka" },
    "sk": { "Name": "Slowakisch", "Source": "Slowakei" },
    "sl": { "Name": "Slowenisch", "Source": "Slowenien" },
    "sm": { "Name": "Samoanisch", "Source": "Samoa" },
    "sn": { "Name": "Shona", "Source": "Simbabwe" },
    "so": { "Name": "Somali", "Source": "Somalia, Dschibuti, Kenia" },
    "sq": { "Name": "Albanisch", "Source": "Albanien, Kosovo" },
    "sr": { "Name": "Serbisch", "Source": "Serbien, Bosnien und Herzegowina" },
    "ss": { "Name": "Swazi", "Source": "Eswatini, Südafrika" },
    "st": { "Name": "Sesotho", "Source": "Lesotho, Südafrika" },
    "su": { "Name": "Sundanesisch", "Source": "Indonesien (Westjava)" },
    "sv": { "Name": "Schwedisch", "Source": "Schweden, Finnland" },
    "sw": { "Name": "Suaheli", "Source": "Ostafrika (Tansania, Kenia, Uganda)" },
    "ta": { "Name": "Tamil", "Source": "Indien (Tamil Nadu), Sri Lanka" },
    "te": { "Name": "Telugu", "Source": "Indien (Andhra Pradesh, Telangana)" },
    "tg": { "Name": "Tadschikisch", "Source": "Tadschikistan" },
    "th": { "Name": "Thailändisch", "Source": "Thailand" },
    "ti": { "Name": "Tigrinya", "Source": "Äthiopien, Eritrea" },
    "tk": { "Name": "Turkmenisch", "Source": "Turkmenistan" },
    "tl": { "Name": "Tagalog", "Source": "Philippinen" },
    "tn": { "Name": "Setswana", "Source": "Botswana, Südafrika" },
    "to": { "Name": "Tonga (Tonga-Inseln)", "Source": "Tonga" },
    "tr": { "Name": "Türkisch", "Source": "Türkei, Zypern" },
    "ts": { "Name": "Tsonga", "Source": "Südafrika, Eswatini, Mosambik" },
    "tt": { "Name": "Tatarisch", "Source": "Russland (Tatarstan)" },
    "tw": { "Name": "Twi", "Source": "Ghana" },
    "ty": { "Name": "Tahitianisch", "Source": "Französisch-Polynesien" },
    "ug": { "Name": "Uigurisch", "Source": "China (Xinjiang)" },
    "uk": { "Name": "Ukrainisch", "Source": "Ukraine" },
    "ur": { "Name": "Urdu", "Source": "Pakistan, Indien" },
    "uz": { "Name": "Usbekisch", "Source": "Usbekistan" },
    "ve": { "Name": "Venda", "Source": "Südafrika" },
    "vi": { "Name": "Vietnamesisch", "Source": "Vietnam" },
    "vo": { "Name": "Volapük", "Source": "Künstliche Sprache, International" },
    "wa": { "Name": "Wallonisch", "Source": "Belgien" },
    "wo": { "Name": "Wolof", "Source": "Senegal, Gambia" },
    "xh": { "Name": "Xhosa", "Source": "Südafrika" },
    "yi": { "Name": "Jiddisch", "Source": "USA, Israel, Osteuropa" },
    "yo": { "Name": "Yoruba", "Source": "Nigeria, Benin" },
    "za": { "Name": "Zhuang", "Source": "China (Guangxi)" },
    "zh": { "Name": "Chinesisch", "Source": "China, Taiwan, Singapur" },
    "zu": { "Name": "Zulu", "Source": "Südafrika" }
}